apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List the files you want to manage
resources:
  - deployment.yaml

# Automatically append a prefix to all resource names
namePrefix: dev-

# Automatically add common labels to every single resource
commonLabels:
  environment: local-dev
